version: '{branch}-rev{build}'

branches:
  only:
    - master
    - development
    - appveyor

max_jobs: 2

image:
  - Ubuntu1804
  - Visual Studio 2019

platform:
  - x64

configuration:
  - Release

install:
  - git submodule init
  - git submodule update --init -- "CMake"
  - ps: $PLATFORM_NAME="x64"
  - ps: $OS_NAME="linux"
  - ps: $PROJECT_DIR="/home/appveyor/projects/rendergraph"
  - ps: if (!$isLinux) {$OS_NAME="win32"}
  - ps: if (!$isLinux) {$PROJECT_DIR="C:\projects\rendergraph"}
  - ps: md build
  - ps: cd build
  - ps: if ($isLinux) {cmake -Wno-dev -G "Unix Makefiles" -DPROJECTS_OUTPUT_DIR=/home/appveyor/projects/rendergraph -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/appveyor/projects/rendergraph/package/rendergraph ../ -DCRG_BUILD_TESTS=ON}
  - ps: if (!$isLinux) {cmake -Wno-dev -G "Visual Studio 16 2019" -DPROJECTS_OUTPUT_DIR=C:\projects\rendergraph -DCMAKE_INSTALL_PREFIX=C:\projects\rendergraph\package\rendergraph -DCRG_BUILD_TESTS=ON ../}

build_script:
  - ps: cd $PROJECT_DIR/build
  - ps: if ($isLinux) {cmake --build . --target install --parallel 4}
  - ps: if (!$isLinux) {cmake --build . --target install --parallel 4 --config Release}

test_script:
  - ps: cd $PROJECT_DIR/build
  - ps: ctest -C Release

after_build:
  - ps: if ($isLinux) {cd /home/appveyor/projects/rendergraph}
  - ps: if (!$isLinux) {cd C:\projects\rendergraph}
  - ps: 7z a RenderGraph-$OS_NAME-$PLATFORM_NAME.zip ./package/rendergraph/*
  - ps: Push-AppveyorArtifact RenderGraph-$OS_NAME-$PLATFORM_NAME.zip
